---
title: "plotly"
output: 
  flexdashboard::flex_dashboard:
    orientation: columns
    vertical_layout: fill
---
Click [here](index.html) to return to the index page!

We're gonna look at the NYC Restaurant Inspections data.
```{r load data}
library(flexdashboard)
library(p8105.datasets)
data("rest_inspec")
library(tidyverse)
library(ggplot2)
```

```{r}
data("rest_inspec")

```

```{r}
rest_inspec <- rest_inspec %>%
  filter(!is.na(score) & 
         boro %in% c("BRONX", "MANHATTAN", "BROOKLYN") &
         cuisine_description %in% c("Mexican", "Chinese", "Japanese", "Italian", "Jewish/Kosher", "Russian", "American", "Middle Eastern", "Spanish", "Greek", "Thai")) %>%
  select(boro, cuisine_description, dba, critical_flag, score, grade)

```

```{r}
print(rest_inspec)
```

Within the `rest_inspec` dataset, there are `r nrow(rest_inspec)` observations and ``r ncol(rest_inspec)`` variables.

### Chart A

```{r most common in each borogh}
ggplot(rest_inspec, aes(fill=cuisine_description, y=..count.., x=boro)) + 
  geom_bar(position="stack") +
  labs(title="Cuisine Distribution by Borough") +
  theme_minimal()
```

### Chart B 

```{r}
ggplot(rest_inspec, aes(x=grade)) + 
  geom_bar() +
  facet_wrap(~boro) +
  labs(title="Distribution of Grades by Borough") +
  theme_minimal()
```

### Chart C

```{r}
ggplot(rest_inspec, aes(x=cuisine_description, y=score)) + 
  geom_boxplot() +
  labs(title="Health Inspection Scores by Cuisine") +
  theme_minimal() +
  theme(axis.text.x=element_text(angle=45, hjust=1))
```
